# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package



on:
  pull_request:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.31
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          version-minor: true

          maven-release-version-number: ${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.0
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@evotm.com"
