on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.2' ]

    name: Maven publish package

    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}

      - name: Maven release
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          mvn release:prepare release:perform