on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.2' ]

    name: Maven publish package

    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ steps.ip.outputs.ipv4 }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}
      - name: Maven release
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          mvn release:prepare release:perform